parameters:
#    scrapper_scrape.example.class: Scrapper\ScrapeBundle\Example

services:
#    scrapper_scrape.example:
#        class: %scrapper_scrape.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
